# Generated by Django 2.1.1 on 2018-10-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rallybooking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
