# Generated by Django 2.1.1 on 2018-10-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rallybooking', '0002_auto_20181005_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='rallybooking',
            name='booked_name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
