# Generated by Django 2.1.1 on 2018-10-05 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rallybooking', '0003_rallybooking_booked_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rally',
            name='added_by_name',
            field=models.CharField(blank=True, editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='rally',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='rally',
            name='end_date',
            field=models.DateField(verbose_name='last night'),
        ),
        migrations.AlterField(
            model_name='rally',
            name='pub_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='date published for booking'),
        ),
        migrations.AlterField(
            model_name='rally',
            name='published_by_name',
            field=models.CharField(blank=True, default='', editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='rally',
            name='start_date',
            field=models.DateField(verbose_name='first night'),
        ),
    ]
